---
- name: Turn a RHEL machine into a RHouter
  hosts: all

  tasks:
    - name: Set Hostname
      include_task: rhel_set_hostname.yaml
      when: set_hostname|bool

    - name: Perform System Update
      include_task: rhel_yum_update.yaml
      when: update_system|bool

    - name: Setup base routing
      include_task: rhel_base_routing.yaml
      when: configure_routing|bool
