---
- name: Turn a RHEL machine into a RHouter
  hosts: all

  handlers:
    - name: Pull in Handlers
      include_tasks: handlers/main.yaml

  tasks:
    - name: Pull in default variables
      include_vars: defaults/main.yaml

    - name: Pull in variables
      include_vars: vars/main.yaml

    - name: Set Hostname
      include_tasks: tasks/rhel_set_hostname.yaml
      when: set_hostname|bool

    - name: Perform System Update
      include_tasks: tasks/rhel_yum_update.yaml
      when: update_system|bool

    - name: Setup base routing
      include_tasks: tasks/rhel_base_routing.yaml
      when: configure_routing|bool

    - name: Configure system interfaces
      include_tasks: tasks/rhel_configure_interfaces.yaml
      when: configure_interfaces|bool

    - name: Setup Firewalld basics
      include_tasks: tasks/rhel_setup_firewalld.yaml
      when: configure_firewall_firewalld|bool

    - name: Configure fail2ban
      include_tasks: tasks/rhel_configure_firewall_fail2ban.yaml
      when: configure_firewall_fail2ban|bool

    - name: Set up DHCP - dhcpd
      include_tasks: tasks/rhel_configure_dhcp_dhcpd.yaml
      when: configure_dhcp_dhcpd|bool
