---
- name: Turn a RHEL machine into a RHouter
  hosts: all
  become: yes

  handlers:
    - name: restart dhcpd
      service:
        name: dhcpd
        state: restarted

    - name: restart dhcpd6
      service:
        name: dhcpd6
        state: restarted

    - name: restart fail2ban
      service:
        name: fail2ban
        state: restarted

    - name: restart BIND
      service:
        name: named
        state: restarted

    - name: restart chronyd
      service:
        name: chronyd
        state: restarted

    - name: restart sshd
      service:
        name: sshd
        state: restarted

    - name: restart openvpn
      systemd:
        name: openvpn@server.service
        state: restarted

    - name: restart nginx
      service:
        name: nginx
        state: restarted

    - name: restart network
      service:
        name: network
        state: restarted

    - name: update-ca-trust
      shell: /bin/update-ca-trust

  tasks:
    - name: Pull in default variables
      include_vars: defaults/main.yaml

    - name: Pull in variables
      include_vars: vars/main.yaml

    - name: Set Hostname
      include_tasks: tasks/rhel_set_hostname.yaml
      when: set_hostname|bool
      tags:
        - setHostname

    - name: Configure system interfaces
      include_tasks: tasks/rhel_configure_interfaces.yaml
      when: configure_interfaces|bool and interface_config_method == "legacy"
      tags:
        - configureInterfaces

    - name: Disable auto dns on WAN
      shell: "nmcli con mod wan-{{ wan_interface }} ipv4.ignore-auto-dns yes"
      ignore_errors: yes

    - name: Disable auto dns on WAN v6
      shell: "nmcli con mod wan-{{ wan_interface }} ipv6.ignore-auto-dns yes"
      ignore_errors: yes

    - name: Configure system interfaces
      include_role:
        name: rhel-system-roles.network
      when: configure_interfaces|bool and interface_config_method == "role"
      tags:
        - configureInterfaces

    - name: Disable auto dns on WAN again
      shell: "nmcli con mod wan-{{ wan_interface }} ipv4.ignore-auto-dns yes"

    - name: Disable auto dns on WAN again v6
      shell: "nmcli con mod wan-{{ wan_interface }} ipv6.ignore-auto-dns yes"

    - name: Set LAN to never-default route
      shell: "nmcli con mod {{ lan_bridge_name }} ipv4.never-default yes && nmcli con mod {{ lan_bridge_name }} ipv6.never-default yes"
    - name: Set OPT1 to never-default route
      shell: "nmcli con mod {{ opt1_bridge_name }} ipv4.never-default yes && nmcli con mod {{ opt1_bridge_name }} ipv6.never-default yes"
      when: enable_opt1_interface|bool and configure_opt1_interface|bool
    - name: Set OPT2 to never-default route
      shell: "nmcli con mod {{ opt2_bridge_name }} ipv4.never-default yes && nmcli con mod {{ opt2_bridge_name }} ipv6.never-default yes"
      when: enable_opt2_interface|bool and configure_opt2_interface|bool

    - name: Restart network after configuring interfaces
      include_tasks: tasks/rhel_restart_network.yaml

    - name: Perform System Update
      include_tasks: tasks/rhel_yum_update.yaml
      when: update_system|bool
      tags:
        - systemUpdate

    - name: Setup Firewalld basics
      include_tasks: tasks/rhel_setup_firewalld.yaml
      when: configure_firewall_firewalld|bool
      tags:
        - configureFirewall
        - configureFirewalld

    - name: Setup base routing
      include_tasks: tasks/rhel_base_routing.yaml
      when: configure_routing|bool
      tags:
        - configureRouting

    - name: Configure fail2ban
      include_tasks: tasks/rhel_configure_firewall_fail2ban.yaml
      when: configure_firewall_fail2ban|bool
      tags:
        - configureFirewall
        - configureFail2ban

    - name: Configure SSHd
      include_tasks: tasks/rhel_configure_sshd.yaml
      when: configure_sshd|bool
      tags:
        - configureSSHd

    - name: Set up DNS - BIND
      include_tasks: tasks/rhel_configure_dns_bind.yaml
      when: configure_dns_bind|bool
      tags:
        - configureDNS
        - configureBIND

    - name: Set up DHCP - dhcpd
      include_tasks: tasks/rhel_configure_dhcp_dhcpd.yaml
      when: configure_dhcp_dhcpd|bool
      tags:
        - configureDHCP
        - configureDHCPd

    - name: Reset BIND/DHCPd connection
      shell: rm -f /var/named/zones/*.jnl && systemctl restart dhcpd && systemctl restart named

    - name: Set up mDNS - Avahi
      include_tasks: tasks/rhel_configure_mdns_avahi.yaml
      when: configure_mdns_avahi|bool
      tags:
        - configuremDNS
        - configureAvahi

    - name: Set WAN to localhost DNS
      shell: "nmcli con mod wan-{{ wan_interface }} ipv4.dns 127.0.0.1"

    - name: Restart network after configuring wan local DNS
      include_tasks: tasks/rhel_restart_network.yaml

    - name: Set up NTP - chronyd
      include_tasks: tasks/rhel_configure_ntp_chrony.yaml
      when: configure_ntp_chrony|bool
      tags:
        - configureNTP
        - configureChronyd

    - name: Setup Cockpit Dashboard
      include_tasks: tasks/rhel_setup_cockpit.yaml
      when: configure_cockpit|bool
      tags:
        - configureCockpit

    - name: Setup Containers
      include_tasks: tasks/rhel_setup_containers.yaml
      when: configure_containers|bool
      tags:
        - configureContainers

    - name: Setup Virtualization - libvirt
      include_tasks: tasks/rhel_configure_libvirt.yaml
      when: configure_virt_libvirt|bool
      tags:
        - configureVirtualization
        - configureLibvirt

    - name: Set up VPN - OpenVPN
      include_tasks: tasks/rhel_configure_openvpn.yaml
      when: configure_openvpn|bool
      tags:
        - configureVPN
        - configureOpenVPN
