---
- name: Check if EPEL repo is already configured
  stat: path={{ epel_repofile_path }}
  register: epel_repofile_result
  tags:
    - installEPEL

- name: Install EPEL repo
  yum:
    name: "{{ epel_repo_url }}"
    state: present
  register: result
  when: not epel_repofile_result.stat.exists
  tags:
    - installEPEL

- name: Import EPEL GPG key
  rpm_key:
    key: "{{ epel_repo_gpg_key_url }}"
    state: present
  when: not epel_repofile_result.stat.exists
  tags:
    - installEPEL

- name: Install fail2ban
  yum:
    name: fail2ban
    state: latest
  tags:
    - installPackages
    - installFail2ban

- name: Template out fail2ban local jail config file
  template:
    src: fail2ban-jail.j2
    dest: /etc/fail2ban/jail.local
    backup: yes
  notify: restart fail2ban

- name: Start and enable fail2ban
  service:
    name: fail2ban
    state: started
    enabled: yes
