---
- name: Set IPv4 Forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    sysctl_set: yes
    state: present
    reload: yes
  when: routing_enable_ipv4|bool

- name: Check that ipv6 is enabled
  stat:
    path: /proc/sys/net/ipv6/conf/all/forwarding
  register: ipv6_check

- name: Set IPv6 Forwarding
  sysctl:
    name: net.ipv6.conf.all.forwarding
    value: "1"
    sysctl_set: yes
    state: present
    reload: yes
  when: routing_enable_ipv6|bool and ipv6_check.stat.exists
