---
- name: Set IPv4 Forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    sysctl_set: yes
    state: present
    reload: yes
  when: routing_enable_ipv4|bool

- name: Disable Reverse Path Filtering
  sysctl:
    name: net.ipv4.conf.all.rp_filter
    value: "0"
    sysctl_set: yes
    state: present
    reload: yes
  when: routing_enable_ipv4|bool

- name: Disable Reverse Path Filtering
  sysctl:
    name: net.ipv4.conf.default.rp_filter
    value: "0"
    sysctl_set: yes
    state: present
    reload: yes
  when: routing_enable_ipv4|bool

- name: Disable Reverse Path Filtering on all interfaces
  shell: |
    for TUNABLE in $(sysctl -a | awk '/\.rp_filter/{print $1}' | grep '^net.*$'); do sysctl -w "$TUNABLE=0"; done 2>/dev/null

- name: Check that ipv6 is enabled
  stat:
    path: /proc/sys/net/ipv6/conf/all/forwarding
  register: ipv6_check

- name: Set IPv6 Forwarding for all
  sysctl:
    name: net.ipv6.conf.all.forwarding
    value: "1"
    sysctl_set: yes
    state: present
    reload: yes
  register: ipv6_forward_all
  until: ipv6_forward_all is not failed
  retries: 5
  when: routing_enable_ipv6|bool and ipv6_check.stat.exists

- name: Check that ipv6 is enabled
  stat:
    path: /proc/sys/net/ipv6/conf/default/forwarding
  register: ipv6_default_check

- name: Set IPv6 Forwarding for default
  sysctl:
    name: net.ipv6.conf.default.forwarding
    value: "1"
    sysctl_set: yes
    state: present
    reload: yes
  register: ipv6_forward_default
  until: ipv6_forward_default is not failed
  retries: 5
  when: routing_enable_ipv6|bool and ipv6_default_check.stat.exists
