---
- name: Install Firewalld
  yum:
    name: firewalld
    state: latest
  tags:
    - installPackages
    - installFirewalld

- name: Enable and start Firewalld
  service:
    name: firewalld
    state: started
    enabled: yes

- name: Create WAN Zone
  firewalld:
    zone: extWAN
    state: present
    permanent: yes
  when: enable_wan_interface|bool and configure_wan_interface|bool

- name: Create LAN Zone
  firewalld:
    zone: intLAN
    state: present
    permanent: yes
  when: enable_lan_interface|bool and configure_lan_interface|bool

- name: Create OPT1 Zone
  firewalld:
    zone: intOPT1
    state: present
    permanent: yes
  when: enable_opt1_interface|bool and configure_opt1_interface|bool

- name: Create OPT2 Zone
  firewalld:
    zone: intOPT2
    state: present
    permanent: yes
  when: enable_opt2_interface|bool and configure_opt2_interface|bool

- name: Enable masquerading on WAN
  firewalld:
    masquerade: "true"
    state: enabled
    permanent: yes
    immediate: yes
    zone: extWAN
  when: enable_wan_interface|bool and configure_wan_interface|bool and configure_routing|bool

- name: Enable OpenVPN on WAN
  firewalld:
    zone: extWAN
    permanent: yes
    immediate: yes
    state: enabled
    service: openvpn
  when: enable_wan_interface|bool and configure_wan_interface|bool and configure_openvpn|bool

- name: Disable OpenVPN on WAN
  firewalld:
    zone: extWAN
    permanent: yes
    immediate: yes
    state: disabled
    service: openvpn
  when: enable_wan_interface|bool and configure_wan_interface|bool and not configure_openvpn|bool

- name: Disable SSH on WAN
  firewalld:
    zone: extWAN
    permanent: yes
    immediate: yes
    state: disabled
    service: ssh
  when: enable_wan_interface|bool and configure_wan_interface|bool and not enable_ssh_on_wan|bool

- name: Enable SSH on WAN
  firewalld:
    zone: extWAN
    permanent: yes
    immediate: yes
    state: enabled
    service: ssh
  when: enable_wan_interface|bool and configure_wan_interface|bool and enable_ssh_on_wan|bool

- name: Enable SSH on LAN
  firewalld:
    zone: intLAN
    permanent: yes
    immediate: yes
    state: enabled
    service: ssh
  when: enable_lan_interface|bool and configure_lan_interface|bool and enable_ssh_on_lan|bool

- name: Enable SSH on OPT1
  firewalld:
    zone: intOPT1
    permanent: yes
    immediate: yes
    state: enabled
    service: ssh
  when: enable_opt1_interface|bool and configure_opt1_interface|bool and enable_ssh_on_opt1|bool

- name: Enable SSH on OPT2
  firewalld:
    zone: intOPT2
    permanent: yes
    immediate: yes
    state: enabled
    service: ssh
  when: enable_opt2_interface|bool and configure_opt2_interface|bool and enable_ssh_on_opt2|bool

- name: Allow DNS on LAN
  firewalld:
    zone: intLAN
    service: dns
    permanent: yes
    immediate: yes
    state: enabled
  when: enable_lan_interface|bool and configure_lan_interface|bool and configure_dns_bind|bool

- name: Allow DNS on OPT1
  firewalld:
    zone: intOPT1
    service: dns
    permanent: yes
    immediate: yes
    state: enabled
  when: enable_opt1_interface|bool and configure_opt1_interface|bool and configure_dns_bind|bool

- name: Allow DNS on OPT2
  firewalld:
    zone: intOPT2
    service: dns
    permanent: yes
    immediate: yes
    state: enabled
  when: enable_opt2_interface|bool and configure_opt2_interface|bool and configure_dns_bind|bool

- name: Allow mDNS on LAN
  firewalld:
    zone: intLAN
    service: mdns
    permanent: yes
    immediate: yes
    state: enabled
  when: enable_lan_interface|bool and configure_lan_interface|bool and configure_mdns_avahi|bool

- name: Allow mDNS on OPT1
  firewalld:
    zone: intOPT1
    service: mdns
    permanent: yes
    immediate: yes
    state: enabled
  when: enable_opt1_interface|bool and configure_opt1_interface|bool and configure_mdns_avahi|bool

- name: Allow mDNS on OPT2
  firewalld:
    zone: intOPT2
    service: mdns
    permanent: yes
    immediate: yes
    state: enabled
  when: enable_opt2_interface|bool and configure_opt2_interface|bool and configure_mdns_avahi|bool

- name: Allow DHCP on LAN
  firewalld:
    zone: intLAN
    service: dhcp
    permanent: yes
    immediate: yes
    state: enabled
  when: enable_lan_interface|bool and configure_lan_interface|bool and configure_dhcp_dhcpd|bool

- name: Allow DHCP on OPT1
  firewalld:
    zone: intOPT1
    service: dhcp
    permanent: yes
    immediate: yes
    state: enabled
  when: enable_opt1_interface|bool and configure_opt1_interface|bool and configure_dhcp_dhcpd|bool

- name: Allow DHCP on OPT2
  firewalld:
    zone: intOPT2
    service: dhcp
    permanent: yes
    immediate: yes
    state: enabled
  when: enable_opt2_interface|bool and configure_opt2_interface|bool and configure_dhcp_dhcpd|bool

- name: Allow NTP on LAN
  firewalld:
    zone: intLAN
    service: ntp
    permanent: yes
    immediate: yes
    state: enabled
  when: enable_lan_interface|bool and configure_lan_interface|bool and configure_ntp_chrony|bool

- name: Allow NTP on OPT1
  firewalld:
    zone: intOPT1
    service: ntp
    permanent: yes
    immediate: yes
    state: enabled
  when: enable_opt1_interface|bool and configure_opt1_interface|bool and configure_ntp_chrony|bool

- name: Allow NTP on OPT2
  firewalld:
    zone: intOPT2
    service: ntp
    permanent: yes
    immediate: yes
    state: enabled
  when: enable_opt2_interface|bool and configure_opt2_interface|bool and configure_ntp_chrony|bool

- name: Allow Cockpit on LAN
  firewalld:
    zone: intLAN
    port: 9090/tcp
    permanent: yes
    immediate: yes
    state: enabled
  when: enable_lan_interface|bool and configure_lan_interface|bool and configure_cockpit|bool

- name: Allow Cockpit on OPT1
  firewalld:
    zone: intOPT1
    port: 9090/tcp
    permanent: yes
    immediate: yes
    state: enabled
  when: enable_opt1_interface|bool and configure_opt1_interface|bool and configure_cockpit|bool

- name: Allow Cockpit on OPT2
  firewalld:
    zone: intOPT2
    port: 9090/tcp
    permanent: yes
    immediate: yes
    state: enabled
  when: enable_opt2_interface|bool and configure_opt2_interface|bool and configure_cockpit|bool

- name: Set WAN zone
  firewalld:
    zone: extWAN
    interface: "{{ wan_interface }}"
    permanent: yes
    immediate: yes
    state: enabled
  when: enable_wan_interface|bool and configure_wan_interface|bool

- name: Set WAN zone (ansible issue 41738 workaround)
  command: "firewall-cmd --zone=extWAN --permanent --change-interface={{ wan_interface }}"
  when: enable_wan_interface|bool and configure_wan_interface|bool

- name: Set LAN zone
  firewalld:
    zone: intLAN
    interface: "{{ lan_interface }}"
    permanent: yes
    immediate: yes
    state: enabled
  when: enable_lan_interface|bool and configure_lan_interface|bool

- name: Set LAN zone (ansible issue 41738 workaround)
  command: "firewall-cmd --zone=intLAN --permanent --change-interface={{ lan_interface }}"
  when: enable_lan_interface|bool and configure_lan_interface|bool

- name: Set LAN zone to target ACCEPT
  command: "firewall-cmd --zone=intLAN --permanent --set-target=ACCEPT"
  when: enable_lan_interface|bool and configure_lan_interface|bool

- name: Set OPT1 zone
  firewalld:
    zone: intOPT1
    interface: "{{ opt1_interface }}"
    permanent: yes
    immediate: yes
    state: enabled
  when: enable_opt1_interface|bool and configure_opt1_interface|bool

- name: Set OPT1 zone (ansible issue 41738 workaround)
  command: "firewall-cmd --zone=intOPT1 --permanent --change-interface={{ opt1_interface }}"
  when: enable_opt1_interface|bool and configure_opt1_interface|bool

- name: Set OPT2 zone
  firewalld:
    zone: intOPT2
    interface: "{{ opt2_interface }}"
    permanent: yes
    immediate: yes
    state: enabled
  when: enable_opt2_interface|bool and configure_opt2_interface|bool

- name: Set OPT2 zone (ansible issue 41738 workaround)
  command: "firewall-cmd --zone=intOPT2 --permanent --change-interface={{ opt2_interface }}"
  when: enable_opt2_interface|bool and configure_opt2_interface|bool

- name: Set default zone to intLAN
  command: "firewall-cmd --set-default-zone intLAN"

- name: Set target for intOPT1
  command: "firewall-cmd --zone=intOPT1 --set-target=ACCEPT --permanent"

- name: Set target for intOPT2
  command: "firewall-cmd --zone=intOPT2 --set-target=ACCEPT --permanent"

- name: Set runtime to permanent
  command: "firewall-cmd --runtime-to-permanent"

- name: Reload firewalld for good measure
  service:
    name: firewalld
    state: restarted
