---
- name: RHEL 7 - Enable needed repos
  rhsm_repository:
    name: ["rhel-7-server-extras-rpms", "rhel-7-server-optional-rpms"]
    state: enabled
  when: ansible_os_family == "RedHat" and ansible_lsb.major_release|int == 7

- name: Install needed packages
  yum:
    name: "{{ cockpit_packages }}"
    state: latest

- name: Enable and start socket
  systemd:
    name: cockpit.socket
    state: started
    enabled: yes
    daemon_reload: yes
