---
- name: RHEL 7 - Enable needed repos
  rhsm_repository:
    name: ["rhel-7-server-extras-rpms", "rhel-7-server-optional-rpms"]
    state: enabled
  when: ansible_os_family == "RedHat" and hostvars[inventory_hostname].ansible_distribution_major_version|int == 7
  tags:
    - configureRepos
    - configureRHEL7ExtrasRepo
    - configureRHEL7OptionalRepo

- name: Install needed packages
  yum:
    name: "{{ cockpit_packages }}"
    state: latest
  tags:
    - installPackages
    - installCockpit

- name: Enable and start socket
  systemd:
    name: cockpit.socket
    state: started
    enabled: yes
    daemon_reload: yes
