---
- name: RHEL 7 - Enable extras repos
  rhsm_repository:
    name: "rhel-7-server-extras-rpms"
    state: enabled
  when: ansible_os_family == "RedHat" and hostvars[inventory_hostname].ansible_distribution_major_version|int == 7
  tags:
    - configureRepos
    - configureRHEL7ExtrasRepo

- name: RHEL 7 - Enable optional repos
  rhsm_repository:
    name: "rhel-7-server-optional-rpms"
    state: enabled
  when: ansible_os_family == "RedHat" and hostvars[inventory_hostname].ansible_distribution_major_version|int == 7
  tags:
    - configureRepos
    - configureRHEL7OptionalRepo

- name: Install needed packages
  yum:
    name: "{{ cockpit_packages }}"
    state: latest
  tags:
    - installPackages
    - installCockpit

- name: Enable and start pmcd
  service:
    name: pmcd
    state: started
    enabled: yes
  when: cockpit_enable_pmcd|bool

- name: Enable and start pmlogger
  service:
    name: pmlogger
    state: started
    enabled: yes
  when: cockpit_enable_pmcd|bool

- name: Enable and start pmproxy
  service:
    name: pmproxy
    state: started
    enabled: yes
  when: cockpit_enable_pmcd|bool

- name: Enable and start socket
  systemd:
    name: cockpit.socket
    state: started
    enabled: yes
    daemon_reload: yes
