---
- name: Install Chronyd
  yum:
    name: chrony
    state: latest
  tags:
    - installPackages
    - installChrony

- name: Configure chronyd
  template:
    src: chrony.conf.j2
    dest: /etc/chrony.conf
    backup: yes
  notify: restart chronyd

- name: Start and enable chronyd
  service:
    name: chronyd
    state: started
    enabled: yes

- name: Set timezone
  shell: "timedatectl set-timezone {{ system_timezone }}"
  tags:
    - setTimezone

- name: Set time to config via NTP
  shell: "timedatectl set-ntp 1"
  tags:
    - setSystemToNTPSync

- name: Force handlers to run
  meta: flush_handlers
