---
- name: Install the Avahi package
  yum:
    name:
      - avahi
      - avahi-tools
      - nss-mdns
    state: latest
  tags:
    - installPackages
    - installAvahi

- name: Start and enable Avahi
  service:
    name: avahi-daemon
    state: started
    enabled: yes
