---
- name: Install BIND packages
  yum:
    name: ["bind", "bind-utils"]
    state: latest
  tags:
    - installPackages
    - installBIND

- name: Template BIND config
  template:
    src: bind-named.conf.j2
    dest: /etc/named.conf
    backup: yes
  notify: restart BIND

- name: Touch log dir
  file:
    path: /var/named/log
    state: directory

- name: Touch log files
  file:
    path: "/var/named/log/{{ item }}"
    state: file
    group: named
    owner: named
  with_items:
    - default
    - auth_servers
    - dnssec
    - zone_transfers
    - ddns
    - client_security
    - rate_limiting
    - rpz
    - dnstap
    - queries
    - query-errors

- name: Start and enable BIND
  service:
    name: named
    state: started
    enabled: yes
