---
- name: Set IPv4 Forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    sysctl_set: yes
    state: present
    reload: yes
  when: routing_enable_ipv4|bool

- name: Set IPv6 Forwarding
  sysctl:
    name: net.ipv6.ip_forward
    value: "1"
    sysctl_set: yes
    state: present
    reload: yes
  when: routing_enable_ipv6|bool
