---
- name: Check for dhcpd package
  shell:
    cmd: "rpm -qa | grep -w dhcp"
    warn: false
  register: dhcp_check
  ignore_errors: yes

- name: Check for python-netaddr package
  shell:
    cmd: "rpm -qa | grep python-netaddr"
    warn: false
  register: python_netaddr_check
  ignore_errors: yes

- name: Install dhcpd
  yum:
    name: ["dhcp", "python-netaddr"]
    state: latest
  tags:
    - installPackages
    - installDHCPd
  when: dhcp_check.rc|bool and python_netaddr_check.rc|bool

- name: Template out dhpcd config file
  template:
    src: dhcpd.conf.j2
    dest: /etc/dhcp/dhcpd.conf
    backup: yes
  notify: restart dhcpd
  when: routing_enable_ipv4|bool

- name: Set permissions for DHCP key
  file:
    path: /etc/dhcp/rndc-keys/rndc.key
    owner: dhcp
    group: dhcp

- name: Start and enable dhcpd
  service:
    name: dhcpd
    state: started
    enabled: yes
  when: routing_enable_ipv4|bool

- name: Template out dhpcd6 config file
  template:
    src: dhcpd6.conf.j2
    dest: /etc/dhcp/dhcpd6.conf
    backup: yes
  when: routing_enable_ipv6|bool
  notify: restart dhcpd6

- name: Start and enable dhcpd6
  service:
    name: dhcpd
    state: started
    enabled: yes
  when: routing_enable_ipv6|bool

- name: Force handlers to run
  meta: flush_handlers
