---
- name: RHEL 7 - Enable needed repos
  rhsm_repository:
    name: rhel-7-server-extras-rpms
    state: enabled
  when: ansible_os_family == "RedHat" and hostvars[inventory_hostname].ansible_distribution_major_version|int == 7
  tags:
    - configureRepos
    - configureRHEL7ExtrasRepo

- name: Install needed container packages
  yum:
    name: "{{ rhel7_container_packages }}"
    state: latest
  when: ansible_os_family == "RedHat" and hostvars[inventory_hostname].ansible_distribution_major_version|int == 7
  tags:
    - installPackages
    - installContainers

- name: Increase user namespaces in hernel
  lineinfile:
    path: /etc/sysctl.d/userns.conf
    line: user.max_user_namespaces=28633
    create: yes

- name: Apply kernel modifications
  shell: sysctl -p /etc/sysctl.d/userns.conf

- name: Authenticate to the Red Hat Registry
  shell: "podman login -u '{{ containers_log_in_username }}' -p '{{ containers_log_in_password_or_token }}' https://registry.redhat.io"
  when: containers_log_in_to_rh_registry|bool
  no_log: true
