---
- name: Check for Avahi package
  shell:
    cmd: "rpm -qa | grep -w avahi"
    warn: false
  register: avahi_check
  ignore_errors: yes

- name: Install the Avahi package
  yum:
    name: avahi
    state: latest
  tags:
    - installPackages
    - installAvahi
  when: avahi_check.rc|bool

- name: Start and enable Avahi
  service:
    name: avahi-daemon
    state: started
    enabled: yes
